# STAGE 1: Build Go app
FROM golang:1.24.5 AS builder

WORKDIR /app

# Copy Go modules first for better caching
COPY go.mod go.sum ./
RUN go mod tidy

# Copy the rest of the project files
COPY . .

# Build for Linux, statically linked binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o social-media-app cmd/main.go

# STAGE 2: Use small image to run the app
FROM alpine:3.20

WORKDIR /app

# Copy only the built binary
COPY --from=builder /app/social-media-app /app/social-media-app

EXPOSE 3015

CMD ["./social-media-app"]